version: "3"

# DISCLAIMER: do not change service names willy nilly, dockerfiles depend on them 

services:
  fastapiserver: 
    build:
      context: ./fastapi_server
      dockerfile: Dockerfile
    volumes:
      - ./fastapi_server:/code/app
    ports:
      - 5001:80
  
  microservice1:
    build:
      context: ./microservice1
      dockerfile: Dockerfile
    volumes:
      - ./microservice1:/code/app
