version: "3"

services:
  fastapiserver: 
    image: v1
    build:
      context: ./fastapi_server
      dockerfile: Dockerfile
    volumes:
      - fastapiapp:/code/app
    ports:
      - 5001:80
volumes:
  fastapiapp:
    ext
