version: "3"

services:
  fastapiserver: 
    image: v1
    build:
      context: ./fastapi_server
      dockerfile: Dockerfile
    volumes:
      - ./fastapi_server:/code/app
    ports:
      - 5001:80





